name: Create Archive
on: 
  push:
    branches:
      - master
jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - id: commit
      uses: prompt/actions-commit-hash@v3
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        filename: 'SympleGraphDisplay-${{ steps.commit.outputs.short }}.zip'
        path: './symplegraphdisplay'
    - name: Upload Release
      uses: ncipollo/release-action@v1.12.0
      with:
        artifacts: "SympleGraphDisplay-${{ steps.commit.outputs.short }}.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
        commit: 'master'
        tag: ${{ steps.commit.outputs.short }}
        makeLatest: true
