name: Build & Publish Package
on:
  push:
    branches:
      - master
    paths:
      - symplegraphdisplay/**
  workflow_dispatch:
jobs:
  release:
    name: Create a github release
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "11"
      - uses: actions/checkout@master
      - name: Expose app version name
        run: echo "VERSION_NAME=$(./gradlew -q app:printVersionName )" >> $GITHUB_ENV
      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: 'zip'
          filename: 'SympleGraphDisplay-${{ env.VERSION_NAME }}.zip'
          path: './symplegraphdisplay'
      - name: Upload Release
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "SympleGraphDisplay-${{ env.VERSION_NAME }}.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
          commit: 'master'
          tag: ${{ env.VERSION_NAME }}
          makeLatest: true

  publish:
    name: Create a github package
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "11"

      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache Gradle and wrapper
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant Permission for Gradlew to Execute
        run: chmod +x gradlew

      - name: Build AAR
        run: bash ./gradlew :symplegraphdisplay:assemble

      - name: Publish to Github Package
        run: bash ./gradlew :symplegraphdisplay:publish